In [2]:
from collections import namedtuple
import random

In [3]:
from collections import namedtuple
import random

Record = namedtuple('Record', 'easy medium nightmare')

def data_stream():
    random_generator = random.Random(42)
    easy = 0
    for _ in range(1000):
        easy += random_generator.randint(0, 2) 
        medium = random_generator.randint(0, 256 - 1)
        nightmare = random_generator.randint(0, 1000 - 1)
        
        yield Record(
            easy=easy,
            medium=medium,
            nightmare=nightmare
        )
        
def easy_stream():
    for record in data_stream():
        yield record.easy
        
def medium_stream():
    for record in data_stream():
        yield record.medium
        
def nightmare_stream():
    for record in data_stream():
        yield record.nightmare

In [4]:
import numpy as np

def get_tuple_stream_mean(stream, number_of_values):
    result = np.zeros(number_of_values, dtype='object')
    count = 0. 
    for streamed_tuple in stream:
        result += streamed_tuple
        count += 1
    return ['{:0.2f}'.format(x) for x in result / count]

In [5]:
# deque example
from collections import deque
a = deque([2,5,6,3,10, 232, 2.1, 23, 23])
a.append(32)
a.pop()
a

deque([2, 5, 6, 3, 10, 232, 2.1, 23, 23])

In [260]:
a.rotate(2)
a

deque([23, 23, 2, 5, 6, 3, 10, 232, 2.1])

In [288]:
b = deque(sorted(a))
print(a)
print(b)

deque([2, 5, 6, 3, 10, 232, 2.1, 23, 23])
deque([2, 2.1, 3, 5, 6, 10, 23, 23, 232])


In [311]:
z = 1
print(b)
print(b.remove(z))

deque([-5, -1, 1, 1, 2, 2.1, 3, 5, 6, 10, 23, 23, 53, 232, 500, 501, 1005, 1005])
None


In [276]:
for i in range(2):
    print(i)

0
1


In [316]:
b

deque([-5, -1, 2, 2.1, 3, 5, 6, 10, 23, 23, 53, 232, 500, 501, 1005, 1005])

In [321]:
b.remove(23)
b

deque([-5, -1, 2.1, 3, 5, 6, 10, 23, 53, 232, 501, 1005])

In [308]:
def get_val_position(arr, val):
    for i in range(len(arr)):
        if val < arr[i]:
            return i
        if (val > arr[len(arr)-1]) | (val == arr[len(arr)-1]):
            return len(arr)
        
def deq_insert_order(deq, val):
    order_ind = get_val_position(deq, val)
    deq.rotate(-order_ind)
    deq.appendleft(val)
    deq.rotate(order_ind)
    return deq

In [309]:
x = 1005
ordered_ind = get_val_position(b,x)
b.rotate(-ordered_ind) #.appendleft(x)
b.appendleft(x)
b.rotate(ordered_ind)
b

deque([-5,
       -1,
       1,
       1,
       2,
       2.1,
       3,
       5,
       6,
       10,
       23,
       23,
       53,
       232,
       500,
       501,
       1005,
       1005])

In [290]:
y = 1
print(b)
c = deq_insert_order(b,y)
print(c)

deque([2, 2.1, 3, 5, 6, 10, 23, 23, 53, 232])
deque([1, 2, 2.1, 3, 5, 6, 10, 23, 23, 53, 232])


In [175]:
a = np.array([2,5,6,3,10, 232, 2.1, 23, 30])
a = np.sort(a)
a

array([   2. ,    2.1,    3. ,    5. ,    6. ,   10. ,   23. ,   30. ,
        232. ])

In [ ]:
np.searchsorted(a,4.5)

In [197]:
b = np.insert(a, np.searchsorted(a,1), 1)
b

array([   1. ,    2. ,    2.1,    3. ,    5. ,    6. ,   10. ,   23. ,
         30. ,  232. ])

In [198]:
b[1:].copy()
b

array([   1. ,    2. ,    2.1,    3. ,    5. ,    6. ,   10. ,   23. ,
         30. ,  232. ])

In [215]:
b = np.append(b,4)
b

array([   1. ,    2. ,    2.1,    3. ,    5. ,    6. ,   10. ,   23. ,
         30. ,  232. ,    4. ])

In [88]:
def mean_var_rolling_generator(stream, WinSize=1000):
    count = 0
    running_sum = 0.0
    running_sq_sum = 0.0
    #arr = np.empty()
    arr = deque()
    for value in stream:
        count +=1
        arr.append(value)
        running_sum += value
        running_sq_sum += value**2
        if count > (WinSize-1):
            yield( running_sum / WinSize, # rolling mean
                   running_sq_sum / WinSize - (running_sum / WinSize)**2 ) # rolling variance
            tmp_out = arr.popleft() # delete leftmoast elem from arr
            running_sum -= tmp_out
            running_sq_sum -= tmp_out**2

In [19]:
# generate stream:
def example_stream():
    random_generator = random.Random(42)
    for _ in range(10):
        out = random_generator.randint(1,11)
        yield(out)

In [20]:
for i in example_stream():
    print(i)

11
2
1
5
4
4
3
2
11
9


In [141]:
ar = np.array([11,2,1,5,4,4,3,2,11,9])
print(ar.mean())
print(ar.var(ddof=0))

5.2
12.76


In [105]:
for j in mean_var_rolling_generator(example_stream(), WinSize=5):
    print(j)

(4.6, 12.240000000000002)
(3.2, 2.1599999999999984)
(3.4, 1.8400000000000016)
(3.6, 1.0399999999999991)
(4.8, 10.160000000000004)
(5.8, 12.560000000000002)


In [90]:
print(get_tuple_stream_mean(mean_var_rolling_generator(medium_stream()), 2))

['130.47', '5447.77']


In [ ]:
def slidingWindow(sequence, winSize, step=1):
    """Returns a generator that will iterate through
    the defined chunks of input sequence. Input sequence
    must be iterable."""
 
    # Verify the inputs
    try: it = iter(sequence)
    except TypeError:
        raise Exception("**ERROR** sequence must be iterable.")
    if not ((type(winSize) == type(0)) and (type(step) == type(0))):
        raise Exception("**ERROR** type(winSize) and type(step) must be int.")
    if step > winSize:
        raise Exception("**ERROR** step must not be larger than winSize.")
    if winSize > len(sequence):
        raise Exception("**ERROR** winSize must not be larger than sequence length.")
    
    # Pre-compute number of chunks to emit
    numOfChunks = ((len(sequence)-winSize)/step)+1
 
    # Do the work
    for i in range(0,numOfChunks*step,step):
        yield sequence[i:i+winSize]

In [158]:
## for easy stream (min, max, median):
def easy_stats_generator(stream, WinSize=1000):
    count = 0
    min_tmp = 0.0
    max_tmp = 0.0
    median_tmp = 0.0
    arr = deque()
    for value in stream:
        arr.append(value)
        count += 1
        if  count > (WinSize - 1):
            median_tmp = arr[WinSize//2]
            max_tmp = arr[-1]
            min_tmp = arr.popleft()
            yield(min_tmp, max_tmp, median_tmp)

In [159]:
for j in easy_stats_generator(example_stream(), WinSize=5):
    print(j)

(11, 4, 1)
(2, 4, 5)
(1, 3, 4)
(5, 2, 4)
(4, 11, 3)
(4, 9, 2)


In [162]:
for i in range(10):
    print(ar[i])

11
2
1
5
4
4
3
2
11
9


In [234]:
def find_right_place(arr, value):
    for j in range(len(arr)):
        if(value < arr[j]):
            return j

def medium_stats_generator(stream, WinSize):
    count = 0
    arr = np.array([])
    index = 
    for value in stream:
        count += 1
        if count < WinSize:
            arr = np.append(arr, value)
        if count == WinSize-1:
            arr = np.sort(arr)
        if count > WinSize-1:
            arr = np.insert(arr, np.searchsorted(arr, value), value)
            #yield (arr[0], arr[-1], arr[WinSize//2])
            yield arr
            arr = arr[1:].copy()

In [235]:
for i in medium_stats_generator(example_stream(),WinSize=5):
    print(i)

[  1.   2.   4.   5.  11.]
[  2.   4.   4.   5.  11.]
[  3.   4.   4.   5.  11.]
[  2.   4.   4.   5.  11.]
[  4.   4.   5.  11.  11.]
[  4.   5.   9.  11.  11.]


In [221]:
for i in example_stream():
    print(i)

11
2
1
5
4
4
3
2
11
9


In [328]:
def get_val_position(arr, val):
    for i in range(len(arr)):
        if val < arr[i]:
            return i
        if (val > arr[len(arr)-1]) | (val == arr[len(arr)-1]):
            return len(arr)
        
def deq_insert_order(deq, val):
    order_ind = get_val_position(deq, val)
    deq.rotate(-order_ind)
    deq.appendleft(val)
    deq.rotate(order_ind)
    return deq

def medium_stats_generator(stream, WinSize=1000):
    count = 0
    deq_sorted = deque()
    deq = deque()
    for value in stream:
        count += 1
        if count < WinSize:
            deq.append(value)
        if count == WinSize-1:
            deq.append(value)
            deq_sorted = deque(sorted(deq))
        if count > WinSize-1:
            deq.append(value) # add new value
            deq_sorted = deq_insert_order(deq_sorted, value) # add new value
            yield (deq_sorted[0], deq_sorted[-1], deq_sorted[WinSize//2])
            # yield deq_sorted
            deq_sorted.remove(deq[0]) # remove first value in deq
            deq.popleft() # remove first_val

In [329]:
for i in medium_stats_generator(example_stream(), WinSize=5):
    print(i)

(1, 11, 4)
(1, 5, 4)
(1, 5, 4)
(2, 5, 4)
(2, 11, 4)
(2, 11, 4)


In [330]:
for i in example_stream():
    print(i)

11
2
1
5
4
4
3
2
11
9


In [ ]:
# change second deque on np array

def get_val_position(arr, val):
    for i in range(len(arr)):
        if val < arr[i]:
            return i
        if (val > arr[len(arr)-1]) | (val == arr[len(arr)-1]):
            return len(arr)
        
def np_insert_order(arr, val):
    np.insert(arr, np.searchsorted(arr,val), val)
    return arr

def medium_stats_generator(stream, WinSize=1000):
    count = 0
    #arr_sorted = np.array()
    deq = deque()
    for value in stream:
        count += 1
        if count < WinSize:
            deq.append(value)
        if count == WinSize-1:
            deq.append(value)
            arr_sorted = np.array(sorted(deq))
        if count > WinSize-1:
            deq.append(value) # add new value
            arr_sorted = arr_insert_order(arr_sorted, value) # add new value
            yield (arr_sorted[0], arr_sorted[-1], arr_sorted[WinSize//2])
            # yield deq_sorted
            arr_sorted.remove(deq[0]) # remove first value in deq
            deq.popleft() # remove first_val

In [338]:
s = np.sort(np.array([1,5,3,10,2,5,0,4]))
x = 3.5
s = np.insert(a, np.searchsorted(a,1), 1) np.insert(a, np.searchsorted(a,1), 1) 

SyntaxError: invalid syntax (<ipython-input-338-2c1a53e25ebe>, line 3)

In [335]:
s

array([ 0,  1,  2,  3,  4,  5,  5, 10])

In [336]:
np.delete(s,0)

array([ 1,  2,  3,  4,  5,  5, 10])

In [337]:
np.delete(s,10)

IndexError: index 10 is out of bounds for axis 0 with size 8

In [ ]:
!conda install tqdm

In [17]:
# change second deque on np array

def get_val_position(arr, val):
    for i in range(len(arr)):
        if val < arr[i]:
            return i
        if (val > arr[len(arr)-1]) | (val == arr[len(arr)-1]):
            return len(arr)
        
def np_insert_order(arr, val):
    arr = np.insert(arr, np.searchsorted(arr,val), val)
    return arr

def np_delete_order(arr, val):
    arr = np.delete( arr, np.searchsorted(arr,val))
    return arr

def medium_stats_generator_2(stream, WinSize=1000):
    count = 0
    #arr_sorted = np.array()
    deq = deque()
    for value in stream:
        count += 1
        if count < WinSize:
            deq.append(value)
        if count == WinSize-1:
            deq.append(value)
            arr_sorted = np.array(sorted(deq))
        if count > WinSize-1:
            deq.append(value) # add new value
            arr_sorted = np_insert_order(arr_sorted, value) # add new value
            yield (arr_sorted[0], arr_sorted[-1], arr_sorted[WinSize//2])
            arr_sorted = np_delete_order(arr_sorted, deq[0]) # remove first value in deq
            deq.popleft() # remove first_val

In [21]:
for i in medium_stats_generator_2(example_stream(), 5):
    print(i)

(1, 11, 4)
(1, 5, 4)
(1, 5, 4)
(2, 5, 4)
(2, 11, 4)
(2, 11, 4)


In [23]:
for i in example_stream():
    print(i)

11
2
1
5
4
4
3
2
11
9
