Нужно реализовать алгоритм для оптимизации бюджета телерекламы (кейс, описанный на семинаре). 
Код для проверки качества представлен в скрипте ad_budget_checker.py, а шаблон, от которого стоит отталкиваться, 
в скрипте ad_budget_example.py. Чекер вашего скрипта должен отработать за 2 минуты на машинке для проверки.
Для сравнения на ad_budget_example.py чекер работает 4 секунды.

In [ ]:
from sklearn.linear_model import LinearRegression  
from scipy.optimize import minimize
import numpy as np


class Optimizer:
    def __init__(self):
        pass

    def optimize(self, origin_budget):
        default_target = self.model.predict([origin_budget])[0]
        random_gen = np.random.RandomState(42)
        best_budget = origin_budget

        for _ in range(2000):
            mask = (random_gen.randint(0, 3, size=len(origin_budget)) - 1) * 0.01 + 1
            new_budget = origin_budget * mask
            if self.model.predict([new_budget])[0] >= default_target and np.sum(best_budget) > np.sum(new_budget):
                best_budget = new_budget

        return best_budget

    def fit(self, X_data, y_data):
self.model = LinearRegression().fit(X_data, y_data)

In [433]:
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error
from sklearn import linear_model
from scipy.optimize import minimize
from sklearn.model_selection import LeavePOut

import numpy as np
import os
import imp
import signal
import traceback
import sys
import json

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

In [399]:
# generate random data: 
random_gen = np.random.RandomState(443)
        
weights = (0.05 + random_gen.exponential(0.75, size=15)) * 2
X_data = random_gen.uniform(0., 4, size=(40, 15))
errors = random_gen.normal(0., 2., size=40)

split_pos = 25
X_train = X_data[:split_pos]
errors_train = errors[:split_pos]
X_test = X_data[split_pos:]
errors_test = errors[split_pos:]

In [400]:
# print(weights, "\n")
# print(X_train, "\n")
# print(errors_train, "\n")
# print(X_test, "\n")
# print(errors_test, "\n")

In [401]:
y_train  = np.dot(X_train, weights)+errors_train
y_test = np.dot(X_test, weights)+errors_test

In [487]:
#lm = linear_model.LinearRegression()
lm = linear_model.Ridge(alpha = 0.8)  # 6.628
#lm = linear_model.Lasso(alpha=0.1) # 4.9
#lm = linear_model.LassoLars(alpha=0.03) # 4.4
#lm = linear_model.BayesianRidge() # 7.2
lm.fit(np.array(X_train), y_train)

Ridge(alpha=0.8, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [488]:
y_pr_tr = lm.predict(X_train)
y_pr_ts = lm.predict(X_test)

In [489]:
print(mean_squared_error(y_train, y_pr_tr))
print(mean_squared_error(y_test, y_pr_ts))

3.603885597072248
9.997920431609307


In [490]:
scores = cross_val_score(lm, X_train, y_train, scoring='mean_squared_error', cv=X_train.shape[0])

C:\Users\Liksakov\AppData\Local\Continuum\anaconda3_2\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\Liksakov\AppData\Local\Continuum\anaconda3_2\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\Liksakov\AppData\Local\Continuum\anaconda3_2\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_squared_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\Liksakov\AppData\Local\Continuum\anaconda3_2\lib\site-packages\sklearn\metrics\scorer.py:100: DeprecationWarning: Scoring method mean_squared_error was renamed to neg_mean_square

In [491]:
print( np.mean(-scores))

25.66148809602838


In [439]:
#Lpo = LeavePOut(p=2)
#for X_tr, X_ts in Lpo.split(X_train):
#    print(X_tr, X_ts, "\n")

In [478]:
# Optimisation
value = 1
origin_budget = np.array([value]*15)
default_target = lm.predict([origin_budget])[0]
random_gen = np.random.RandomState(41)
best_budget = origin_budget

In [481]:
# metrics which we want to keep at the same level 
print(round(default_target,0))
print(round(sum(origin_budget)))

20.0
15


In [461]:
mask = (random_gen.randint(0, 3, size=len(origin_budget)) - 1) * 0.01 + 1

In [482]:
new_budget = origin_budget * mask

In [484]:
new_budget

array([0.99, 0.99, 1.01, 0.99, 1.  , 1.  , 1.  , 1.01, 1.  , 0.99, 0.99,
       1.01, 1.01, 0.99, 0.99])

In [492]:
lm.fit(np.array(X_train), y_train)

Ridge(alpha=0.8, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [497]:
print(lm.intercept_)
lm.coef_

-4.4030644241724985


array([ 2.52546014,  3.04589199,  0.7483945 ,  1.47472866,  1.49521371,
        0.33893652,  2.02608061,  1.59913891,  1.85067215,  2.23808624,
        3.88330154,  0.69603392,  1.0665968 , -0.12106176,  1.51434758])

In [502]:
-coefs

array([-2.52546014, -3.04589199, -0.7483945 , -1.47472866, -1.49521371,
       -0.33893652, -2.02608061, -1.59913891, -1.85067215, -2.23808624,
       -3.88330154, -0.69603392, -1.0665968 ,  0.12106176, -1.51434758])

In [500]:
coefs = lm.coef_
interc = lm.intercept_

In [504]:
A = np.matrix(-coefs)

In [505]:
A.shape

(1, 15)

In [ ]:
A_ub = -coefs

In [517]:
from scipy.optimize import linprog
res = linprog(c=coefs, A_ub = np.matrix(-coefs), b_ub= interc - default_target)

In [529]:
optimal_budget = res.x

In [535]:
target = lm.predict(optimal_budget.reshape(1, -1))[0]
print("New metrics value:", target)
print("Old metrics value:", default_target, "\n")
print("New budget = ", np.sum((optimal_budget)))
print("Old budget = ", np.sum(origin_budget))

New metrics value: 19.97875707420165
Old metrics value: 19.97875707420165 

New budget =  6.2786320478319135
Old budget =  15
